/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import entity.User;
import helper.Validator;

/**
 *
 * @author Jhiven Agnar
 */
public class BuatPost extends javax.swing.JPanel {

    private Validator validator = new Validator();
    private NavbarLayout navbarLayout;

    /**
     * Creates new form BuatPostPanel
     */
    public BuatPost(NavbarLayout navbarLayout) {
        initComponents();
        this.navbarLayout = navbarLayout;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        content = new javax.swing.JPanel();
        txtJudul = new javax.swing.JLabel();
        tfJudul = new javax.swing.JTextField();
        txtNama = new javax.swing.JLabel();
        tfNama = new javax.swing.JTextField();
        txtKategori = new javax.swing.JLabel();
        txtAlamat = new javax.swing.JLabel();
        tfAlamat = new javax.swing.JTextField();
        txtDeskripsi = new javax.swing.JLabel();
        cbKategori = new javax.swing.JComboBox<>();
        btnSubmit = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        fotoContainer = new javax.swing.JPanel();
        imageUpload = new component.ImageUpload();
        displayFoto = new component.ImageDisplay();
        lblTitle = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tfDeskripsi = new javax.swing.JTextArea();

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        content.setBackground(new java.awt.Color(241, 241, 241));

        txtJudul.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtJudul.setForeground(new java.awt.Color(48, 50, 63));
        txtJudul.setText("Judul");

        tfJudul.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tfJudul.setForeground(new java.awt.Color(48, 50, 63));

        txtNama.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtNama.setForeground(new java.awt.Color(48, 50, 63));
        txtNama.setText("Nama Barang");

        tfNama.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tfNama.setForeground(new java.awt.Color(48, 50, 63));

        txtKategori.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtKategori.setForeground(new java.awt.Color(48, 50, 63));
        txtKategori.setText("Kategori");

        txtAlamat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtAlamat.setForeground(new java.awt.Color(48, 50, 63));
        txtAlamat.setText("Alamat");

        tfAlamat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tfAlamat.setForeground(new java.awt.Color(48, 50, 63));

        txtDeskripsi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtDeskripsi.setForeground(new java.awt.Color(48, 50, 63));
        txtDeskripsi.setText("Deskripsi");

        cbKategori.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbKategori.setForeground(new java.awt.Color(48, 50, 63));
        cbKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lost", "Found" }));

        btnSubmit.setBackground(new java.awt.Color(255, 151, 23));
        btnSubmit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnKembali.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnKembali.setForeground(new java.awt.Color(48, 50, 63));
        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        fotoContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imageUpload.setPlaceholder("/resources/no_image.jpg");
        fotoContainer.add(imageUpload, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, -1, -1));

        displayFoto.setSize(200,200);
        displayFoto.rounded = false;

        imageUpload.setImageDisplay(displayFoto);
        fotoContainer.add(displayFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 200));

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitle.setText("Buat Post");

        tfDeskripsi.setColumns(20);
        tfDeskripsi.setLineWrap(true);
        tfDeskripsi.setRows(5);
        jScrollPane3.setViewportView(tfDeskripsi);

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addComponent(lblTitle)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(contentLayout.createSequentialGroup()
                        .addComponent(fotoContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                                .addComponent(btnKembali)
                                .addGap(18, 18, 18)
                                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(contentLayout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(txtJudul, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfJudul)
                                    .addComponent(txtNama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfNama)
                                    .addComponent(txtKategori, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtAlamat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfAlamat)
                                    .addComponent(txtDeskripsi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbKategori, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(20, 20, 20))))
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblTitle)
                .addGap(20, 20, 20)
                .addComponent(txtJudul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addComponent(tfJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNama)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNama, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtKategori)
                        .addGap(8, 8, 8)
                        .addComponent(cbKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtAlamat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDeskripsi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnKembali, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20))
                    .addGroup(contentLayout.createSequentialGroup()
                        .addComponent(fotoContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
        );

        jScrollPane1.setViewportView(content);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        navbarLayout.switchPage("myPost");
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        User user = navbarLayout.getUserController().getCurrentUser();
        String judul = tfJudul.getText();
        String namaBarang = tfNama.getText();
        String alamat = tfAlamat.getText();
        String pathFoto = imageUpload.getImagePath();
        String deskripsi = tfDeskripsi.getText();
        String kategori = cbKategori.getSelectedItem().toString();

        if (!validator.validatePostData(judul, namaBarang, alamat, deskripsi)) {
            return;
        }

        navbarLayout.getPostController().addPost(user, judul, namaBarang, alamat, pathFoto, deskripsi, kategori);
        navbarLayout.switchPage("myPost");
    }//GEN-LAST:event_btnSubmitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> cbKategori;
    private javax.swing.JPanel content;
    private component.ImageDisplay displayFoto;
    private javax.swing.JPanel fotoContainer;
    private component.ImageUpload imageUpload;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField tfAlamat;
    private javax.swing.JTextArea tfDeskripsi;
    private javax.swing.JTextField tfJudul;
    private javax.swing.JTextField tfNama;
    private javax.swing.JLabel txtAlamat;
    private javax.swing.JLabel txtDeskripsi;
    private javax.swing.JLabel txtJudul;
    private javax.swing.JLabel txtKategori;
    private javax.swing.JLabel txtNama;
    // End of variables declaration//GEN-END:variables
}
