/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import entity.Post;
import helper.Validator;

/**
 *
 * @author asus
 */
public class EditPost extends javax.swing.JPanel {

    private Validator validator = new Validator();
    private NavbarLayout navbarLayout;
    private Post post;

    public EditPost(NavbarLayout navbarLayout) {
        initComponents();

        this.navbarLayout = navbarLayout;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        checkDitemukan = new javax.swing.JCheckBox();
        txtDitemukan = new javax.swing.JLabel();
        txtDeskripsi = new javax.swing.JLabel();
        tfJudul = new javax.swing.JTextField();
        tfNama = new javax.swing.JTextField();
        txtJudul = new javax.swing.JLabel();
        txtNama = new javax.swing.JLabel();
        txtKategori = new javax.swing.JLabel();
        cbKategori = new javax.swing.JComboBox<>();
        txtAlamat = new javax.swing.JLabel();
        tfAlamat = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        fotoContainer = new javax.swing.JPanel();
        imgUpload = new component.ImageUpload();
        imgDisplay = new component.ImageDisplay();
        btnSimpan = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tfDeskripsi = new javax.swing.JTextArea();

        txtDitemukan.setText("Telah Ditemukan");

        txtDeskripsi.setText("Deskripsi");

        txtJudul.setText("Judul");

        txtNama.setText("Nama Barang");

        txtKategori.setText("Kategori");

        cbKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lost", "Found" }));

        txtAlamat.setText("Alamat");

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitle.setText("Edit Post");

        fotoContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        fotoContainer.add(imgUpload, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, -1));

        imgDisplay.setSize(170,170);
        imgDisplay.rounded = false;
        fotoContainer.add(imgDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 170));

        btnSimpan.setBackground(new java.awt.Color(255, 151, 23));
        btnSimpan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnKembali.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnKembali.setForeground(new java.awt.Color(48, 50, 63));
        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        tfDeskripsi.setColumns(20);
        tfDeskripsi.setLineWrap(true);
        tfDeskripsi.setRows(5);
        jScrollPane1.setViewportView(tfDeskripsi);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitle)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fotoContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfNama)
                            .addComponent(tfAlamat, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNama)
                                    .addComponent(txtJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(tfJudul))
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(txtKategori)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtDitemukan)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(checkDitemukan))
                                    .addComponent(txtDeskripsi, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 52, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fotoContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtJudul)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNama)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNama, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAlamat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkDitemukan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDitemukan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDeskripsi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        String judul = tfJudul.getText();
        String namaBarang = tfNama.getText();
        String alamat = tfAlamat.getText();
        String pathFoto = imgUpload.getImagePath();
        String deskripsi = tfDeskripsi.getText();
        String kategori = cbKategori.getSelectedItem().toString();

        if (!validator.validatePostData(judul, namaBarang, alamat, deskripsi)) {
            return;
        }

        post.setJudul(judul);
        post.setNamaBarang(namaBarang);
        post.setAlamat(alamat);
        post.setKategori(kategori);
        post.setTelahDitemukan(checkDitemukan.isSelected());
        post.setDeskripsi(deskripsi);
        post.setPathFoto(pathFoto);

        navbarLayout.switchPage("myPost");
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        navbarLayout.switchPage("myPost");
    }//GEN-LAST:event_btnKembaliActionPerformed

    public void setPost(Post post) {
        this.post = post;

        imgUpload.setPlaceholder(post.getPathFoto());
        imgUpload.setImageDisplay(imgDisplay);

        tfAlamat.setText(post.getAlamat());
        tfJudul.setText(post.getJudul());
        tfDeskripsi.setText(post.getDeskripsi());
        cbKategori.setSelectedItem(post.getKategori());
        tfNama.setText(post.getNamaBarang());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cbKategori;
    private javax.swing.JCheckBox checkDitemukan;
    private javax.swing.JPanel fotoContainer;
    private component.ImageDisplay imgDisplay;
    private component.ImageUpload imgUpload;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField tfAlamat;
    private javax.swing.JTextArea tfDeskripsi;
    private javax.swing.JTextField tfJudul;
    private javax.swing.JTextField tfNama;
    private javax.swing.JLabel txtAlamat;
    private javax.swing.JLabel txtDeskripsi;
    private javax.swing.JLabel txtDitemukan;
    private javax.swing.JLabel txtJudul;
    private javax.swing.JLabel txtKategori;
    private javax.swing.JLabel txtNama;
    // End of variables declaration//GEN-END:variables
}
