/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import entity.Post;
import helper.ImageManipulator;
import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author hp
 */
public class MyPostItem extends javax.swing.JPanel {

    private NavbarLayout navbarLayout;
    private Post post;

    public MyPostItem(NavbarLayout navbarLayout, Post post) {
        initComponents();
        
        this.navbarLayout = navbarLayout;
        this.post = post;
        updateData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFoto = new javax.swing.JLabel();
        lblJudul = new javax.swing.JLabel();
        lblNamaBarang = new javax.swing.JLabel();
        lblKategori = new javax.swing.JLabel();
        lblTanggal = new javax.swing.JLabel();

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(200, 200, 200), 1, true));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        lblFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblJudul.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblJudul.setText("Ini Bagian Judul");

        lblNamaBarang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNamaBarang.setText("Ini Bagian Nama Barang");

        lblKategori.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblKategori.setText("Ini Kategori");

        lblTanggal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTanggal.setText("Ini Tanggal");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblJudul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNamaBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addComponent(lblFoto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblJudul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNamaBarang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKategori)
                    .addComponent(lblTanggal))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        navbarLayout.viewPost(post);
    }//GEN-LAST:event_formMouseClicked

     private void updateData() {
        if (post.getPathFoto().isBlank()) {
            lblFoto.setIcon(null);
        } else {
            lblFoto.setIcon(new ImageIcon(new ImageManipulator(post.getPathFoto()).resize(200, 200).getImage()));
        }

        lblKategori.setText(post.getKategori());
        if (post.getKategori().equals("Lost")) {
            lblKategori.setBackground(Color.red);
        } else {
            lblKategori.setBackground(Color.green);
        }

        lblJudul.setText(post.getJudul());
        lblNamaBarang.setText(post.getNamaBarang());
        lblTanggal.setText(post.getRelativeTime());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblKategori;
    private javax.swing.JLabel lblNamaBarang;
    private javax.swing.JLabel lblTanggal;
    // End of variables declaration//GEN-END:variables
}
