/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package component;

import helper.ImageManipulator;
import javax.swing.ImageIcon;

/**
 *
 * @author wisnu
 */
public class AvatarImage extends javax.swing.JPanel {

    private String imagePath;
    private int width = 94;
    private int height = 94;

    /**
     * Creates new form AvatarImage
     */
    public AvatarImage() {
        initComponents();
    }

    public void setImage(String path) {
        imagePath = path;
        updateImage();
    }

    public ImageIcon getImage() {
        ImageManipulator manipulator = new ImageManipulator(imagePath);
        manipulator.resize(this.width, this.height);
        manipulator.setRoundedCorner(this.height);

        return new ImageIcon(manipulator.getImage());
    }

    private void updateImage() {
        if (imagePath.isBlank()) {
            lblFoto.setIcon(null);
        } else {
            lblFoto.setIcon(getImage());
        }
    }

    public void setSize(int width, int height) {
        this.width = width;
        this.height = height;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFoto = new javax.swing.JLabel();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblFoto, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblFoto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblFoto;
    // End of variables declaration//GEN-END:variables
}
