/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package kelompok_empat.component;

import java.awt.Graphics2D;
import java.awt.geom.RoundRectangle2D;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;

/**
 *
 * @author wisnu
 */
public class AvatarImage extends javax.swing.JPanel {

    private String imagePath;
    private int width = 94;
    private int height = 94; 

    /**
     * Creates new form AvatarImage
     */
    public AvatarImage() {
        initComponents();
    }

    public void setImage(String path) {
        imagePath = path;
        updateImage();
    }

    public ImageIcon getImage(ImageIcon originalIcon) {
        BufferedImage image = new BufferedImage(this.width, this.height, BufferedImage.TYPE_INT_ARGB);
        Graphics2D g2d = image.createGraphics();
        RoundRectangle2D roundedRectangle = new RoundRectangle2D.Float(0, 0, this.width, this.height, this.width, this.height);
        g2d.setClip(roundedRectangle);
        originalIcon.paintIcon(null, g2d, 0, 0);
        g2d.dispose();

        return new ImageIcon(image);
    }

    private void updateImage() {
        lblFoto.setIcon(getImage(new ImageIcon(new ImageResizer(imagePath).resize(this.width, this.height))));
    }
    
    public void setSize(int width, int height){
        this.width = width;
        this.height = height;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFoto = new javax.swing.JLabel();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblFoto, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblFoto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblFoto;
    // End of variables declaration//GEN-END:variables
}
